name: KanaChat
version: 2.0.3
author: fubira
main: net.ironingot.kanachat.KanaChat
description: Alphabet to Hiragana convert + Kanji Translation
commands:
  kanachat:
    aliases:
      - japanize
      - kc
    usage: |
      /<command> [on|off] 
      /<command> kanji [on|off]
    description: Enable or Disable roma-ji japanese translation
